server:
  port: ${PORT}

amazonSES:
  accessKey: ${SES_ACCESS_KEY}
  secretKey: ${SES_SECRET_KEY}
  region: ${SES_REGION}

email:
  sender: ${EMAIL_SENDER}
  requestTimeout: ${EMAIL_REQUEST_TIMEOUT}

twilio:
  accountSId: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: ${TWILIO_PHONE_NUMBER}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        specific.avro.reader: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: demo